In [46]:
import pandas as pd

df = pd.read_excel("DanhSachSinhVien.xlsx")
df.columns

Index(['Stt', 'Mã SV', 'Họ lót', 'Tên', 'Mã lớp', 'Tên lớp', 'Điện thoại',
       'Email', 'Chuyên cần (20%)', 'BC giữa kì (30%)', 'BC cuối kì (50%)',
       'TỔNG'],
      dtype='object')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Stt               84 non-null     int64
 1   Mã SV             83 non-null     float64
 2   Họ lót            84 non-null     object
 3   Tên               83 non-null     object
 4   Mã lớp            81 non-null     object
 5   Tên lớp           81 non-null     object
 6   Điện thoại        79 non-null     float64
 7   Email             69 non-null     object
 8   Chuyên cần (20%)  82 non-null     float64
 9   BC giữa kì (30%)  82 non-null     float64
 10  BC cuối kì (50%)  82 non-null     float64
 11  TỔNG              82 non-null     float64
dtypes: float64(6), int64(1), object(5)
memory usage: 8.0+ KB

In [48]:
import numpy as np
df['Chuyên cần (20%)'] = df['Chuyên cần (20%)'].replace(np.nan, 0)
df['BC giữa kì (30%)'] = df['BC giữa kì (30%)'].replace(np.nan, 0)
df['BC cuối kì (50%)'] = df['BC cuối kì (50%)'].replace(np.nan, 0)

In [49]:
df['Họ và tên'] = df['Họ lót'] + ' ' + df['Tên']
df = df.drop(df.columns[[0, 1, 2, 3, 5, 6, 7]], axis = 1)
df

,Mã lớp,Chuyên cần (20%),BC giữa kì (30%),BC cuối kì (50%),TỔNG,Họ và tên
0,DH22HM,10.0,7.0,4.2,6.20,VÕ THỊ THÚY AN
1,DH22HM,10.0,8.5,5.0,7.05,NGUYỄN THỊ KIM ANH
2,DH22HM,10.0,8.5,3.8,6.45,NGUYỄN NGỌC ẤN
3,DH20HM,10.0,7.0,6.2,7.20,Võ Ngọc Châu
4,DH22HM,10.0,7.5,7.1,7.80,LÊ VĂN CHƯƠNG
...,...,...,...,...,...,...
79,DH22HM,10.0,8.5,4.1,6.60,TRẦN DƯƠNG VINH
80,DH22HM,10.0,9.0,5.1,7.25,NGUYỄN NHẬT VŨ
81,NaN,10.0,7.5,5.3,6.90,Trần Sang Xuân
82,DH22HM,10.0,8.0,6.5,7.65,VÕ THỊ NHƯ Ý
83,DH22HM,10.0,7.0,4.2,6.20,BÙI THỊ YẾN

In [59]:
df['Mã lớp'] = np.where(df['Họ và tên'].str.isupper(), 'DH22HM', 'DH20HM')
# or df.loc[:, 'Mã lớp'] = np.where(df['Họ và tên'].str.isupper(), 'DH22HM', 'DH20HM')
df

C:\Users\peter\AppData\Local\Temp\ipykernel_12604\2868146780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Mã lớp'] = np.where(df['Họ và tên'].str.isupper(), 'DH22HM', 'DH20HM')

,Họ và tên,Mã lớp,Chuyên cần (20%),BC giữa kì (30%),BC cuối kì (50%)
0,VÕ THỊ THÚY AN,DH22HM,10.0,7.0,4.2
1,NGUYỄN THỊ KIM ANH,DH22HM,10.0,8.5,5.0
2,NGUYỄN NGỌC ẤN,DH22HM,10.0,8.5,3.8
3,Võ Ngọc Châu,DH20HM,10.0,7.0,6.2
4,LÊ VĂN CHƯƠNG,DH22HM,10.0,7.5,7.1
...,...,...,...,...,...
79,TRẦN DƯƠNG VINH,DH22HM,10.0,8.5,4.1
80,NGUYỄN NHẬT VŨ,DH22HM,10.0,9.0,5.1
81,Trần Sang Xuân,DH20HM,10.0,7.5,5.3
82,VÕ THỊ NHƯ Ý,DH22HM,10.0,8.0,6.5
83,BÙI THỊ YẾN,DH22HM,10.0,7.0,4.2

In [60]:
df = df[['Họ và tên', 'Mã lớp', 'Chuyên cần (20%)', 'BC giữa kì (30%)', 'BC cuối kì (50%)']]
df

,Họ và tên,Mã lớp,Chuyên cần (20%),BC giữa kì (30%),BC cuối kì (50%)
0,VÕ THỊ THÚY AN,DH22HM,10.0,7.0,4.2
1,NGUYỄN THỊ KIM ANH,DH22HM,10.0,8.5,5.0
2,NGUYỄN NGỌC ẤN,DH22HM,10.0,8.5,3.8
3,Võ Ngọc Châu,DH20HM,10.0,7.0,6.2
4,LÊ VĂN CHƯƠNG,DH22HM,10.0,7.5,7.1
...,...,...,...,...,...
79,TRẦN DƯƠNG VINH,DH22HM,10.0,8.5,4.1
80,NGUYỄN NHẬT VŨ,DH22HM,10.0,9.0,5.1
81,Trần Sang Xuân,DH20HM,10.0,7.5,5.3
82,VÕ THỊ NHƯ Ý,DH22HM,10.0,8.0,6.5
83,BÙI THỊ YẾN,DH22HM,10.0,7.0,4.2

In [61]:
CC = df['Chuyên cần (20%)']
CC

0     10.0
1     10.0
2     10.0
3     10.0
4     10.0
      ...
79    10.0
80    10.0
81    10.0
82    10.0
83    10.0
Name: Chuyên cần (20%), Length: 84, dtype: float64

In [62]:
GK = df['BC giữa kì (30%)']
GK

0     7.0
1     8.5
2     8.5
3     7.0
4     7.5
     ...
79    8.5
80    9.0
81    7.5
82    8.0
83    7.0
Name: BC giữa kì (30%), Length: 84, dtype: float64

In [63]:
CK = df['BC cuối kì (50%)']
CK

0     4.2
1     5.0
2     3.8
3     6.2
4     7.1
     ...
79    4.1
80    5.1
81    5.3
82    6.5
83    4.2
Name: BC cuối kì (50%), Length: 84, dtype: float64

In [64]:
sum((0 < CK) & (CK < 5))

10

In [67]:
df[df['Mã lớp'] == 'DH20HM']

,Họ và tên,Mã lớp,Chuyên cần (20%),BC giữa kì (30%),BC cuối kì (50%)
3,Võ Ngọc Châu,DH20HM,10.0,7.0,6.2
6,Đỗ Thị Diễn,DH20HM,10.0,8.5,7.1
9,Vũ Hoàng Đạt,DH20HM,10.0,8.5,5.0
14,Nguyễn Thị Thu Hà,DH20HM,10.0,7.0,6.7
21,Võ Nguyễn Quang Khải,DH20HM,10.0,8.0,5.9
26,Võ Tùng Lâm,DH20HM,10.0,8.0,7.0
39,Võ Thị Ngọc Nga,DH20HM,10.0,8.0,5.2
45,Nguyễn Trọng Nguyên,DH20HM,10.0,7.0,4.9
54,Đỗ Văn Quốc,DH20HM,10.0,8.0,6.1
55,Phạm Văn Quý,DH20HM,10.0,8.0,5.9
59,Hồ Quang Thiện,DH20HM,10.0,8.0,7.1
61,Huỳnh Anh Thư,DH20HM,10.0,8.0,5.1
64,Nông Hồng Tân Tiến,DH20HM,0.0,0.0,0.0
68,Phan Thị Quỳnh Trang,DH20HM,10.0,8.0,6.1
81,Trần Sang Xuân,DH20HM,10.0,7.5,5.3